#include "parser.h"

struct commands commands = {
	    .abort = 0,
	    .ota = 0,
	    .pa_mode = {
			.set = 0,
			.min = 0,
			.max = 1,
			.type = VALUE_TYPE_INTEGER,
			.name = "pa-mode",
			.help = "set pa-mode <pa>: 0 uses highest power PA, 1 next highest, etc.",
			},
	    .pa_input = {
			 .set = 0,
			 .min = 0,
			 .max = 1,
			 .type = VALUE_TYPE_PA_INPUT,
			 .name = "pa-input",
			 .help = "set pa-input <input>: 0, 1, VBAT or DCDC",
			 },
	    .tx_power = {
			 .set = 0,
			 .min = -32768,
			 .max = 32767,
			 .type = VALUE_TYPE_FLOAT,
			 .conversion = 10.0,
			 .name = "tx-power",
			 .help  = "set tx-power <dBm>: requested TX power in dBm, useful range -27 to 20",
			 },
	    .em2_debug = {
			  .set = 0,
			  .min = 0,
			  .max = 1,
			  .type = VALUE_TYPE_ENABLE,
			  .name = "em2-debug",
			  .help = "set em2-debug <enable>: 0, 1, disable or enable",
			  },
	    .connection_interval = {
				    .set = 0,
				    .min = 6,
				    .max = 3200,
				    .type = VALUE_TYPE_FLOAT,
				    .conversion = 0.8,
				    .name = "connection-interval",
				    .help = "set connection-interval <ms>: 7.5 to 4000",
				    },
	    .adv_interval = {
			     .set = 0,
			     .min = 0x20,
			     .max = 0xffff,
			     .type = VALUE_TYPE_FLOAT,
			     .conversion = 1.6,
			     .name = "adv-interval",
			     .help = "set adv-interval <ms>: 20 to 30000",
			     },
	    .adv_length = {
			   .set = 0,
			   .min = 0,
			   .max = 31,
			   .type = VALUE_TYPE_INTEGER,
			   .name = "adv-length",
			   .help = "set adv-length <payload-size>: 0 to 31",
			   },
	    .stay_connected = {
			       .set = 0,
			       .min = 623,
			       .max = 0x7fffffff,
			       .type = VALUE_TYPE_FLOAT,
			       .name = "stay-connected",
			       .help = "set stay-connected <seconds>: duration to remain connected",
			       },
	    .stay_em1 = {
			       .set = 0,
			       .min = 623,
			       .max = 0x7fffffff,
			       .type = VALUE_TYPE_FLOAT,
			       .name = "stay-em1",
			       .help = "set stay-em1 <seconds>: duration to remain in EM1 before advertising",
			       },
	    .stay_em2 = {
			       .set = 0,
			       .min = 623,
			       .max = 0x7fffffff,
			       .type = VALUE_TYPE_FLOAT,
			       .name = "stay-em2",
			       .help = "set stay-em2 <seconds>: duration to remain in EM2 before advertising",
			       },
	    .stay_em3 = {
			       .set = 0,
			       .min = 623,
			       .max = 0x7fffffff,
			       .type = VALUE_TYPE_FLOAT,
			       .name = "stay-em3",
			       .help = "set stay-em3 <seconds>: duration to remain in EM3 before advertising",
			       },
	    .stay_em4h = {
			       .set = 0,
			       .min = 623,
			       .max = 0x7fffffff,
			       .type = VALUE_TYPE_FLOAT,
			       .name = "stay-em4",
			       .help = "set stay-em4h <seconds>: duration to remain in EM4H before advertising",
			       },
	    .stay_em4s = {
			       .set = 0,
			       .min = 623,
			       .max = 0x7fffffff,
			       .type = VALUE_TYPE_FLOAT,
			       .name = "stay-em4s",
			       .help = "set stay-em4s <seconds>: duration to remain in EM4S before advertising",
			       },
};
  
